name: PR Auto-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Node.js version 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependancies
        run: ./install.sh

      - name: Build
        run: ./build.sh
        env:
          AWS_ACCESS_KEY_ID: xxxxxxxxxxxxx
          AWS_SECRET_ACCESS_KEY: xxxxxxxxxxx
